config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :members
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :members, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do
  root to: 'homes#top'
  resources :genres, only: [:index, :create, :edit, :update]
  resources :members, only: [:index, :show, :edit, :update]
  resources :hobbyposts, only: [:index, :show, :update]
  resources :comments, only: [:index, :show, :update]
 end

 scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  resources :comments, only: [:show, :create]
  resources :members, only: [:show, :edit, :update]
  get '/members/:id/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
  patch '/members/:id/withdrawal' => 'members#withdrawal', as: 'withdrawal'
  resources :hobbyposts do
  resource :favorites, only: [:create, :destroy]
  end
 end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :hobbypost
  
  enum is_active: { on: true,  off: false }
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
 
 def index
  @comments = Comment.page(params[:page]).per(10)
 end

 def show
  @comment = Comment.find(params[:id])
 end

 def update
  @comment = Comment.find(params[:id])
  if @comment.update(comment_params)
   redirect_to admin_comments_path
   flash[:notice] = "ステータスを更新しました。"
  else
   render :index
  end
 end

 private
 def comment_params
  params.require(:comment).permit(:is_active)
 end
 
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-2 mt-3">
   <table class ="table-sm table-borderless">
    <thead>
     <th class="table-active h5">コメント一覧</th>
    </thead>
   </table>
  </div>
 </div>

 <div class="row">
  <div class="col-sm-12 mt-3"></div>
    <table class = "table table-borderless">
     <thead class = "thead-light">
      <tr>
       <th>コメントID</th>
       <th>ニックネーム</th>
       <th>投稿内容</th>
       <th>ステータス</th>
      </tr>
     </thead>

     <tbody>
      <% @comments.each do |comment| %>
      <tr>
       <td><%= comment.id %></td>
       <td><%= comment.member.nickname %></td>
       <td><%= link_to comment.content, admin_comment_path(comment.id) %></td>
       <td><%= comment.is_active %></td>
      </tr>
      <% end %>
     </tbody>
    </table>
  </div>
 </div>

 <div class="row">
  <div class="col-sm-12 mt-3">
   <div class="d-flex justify-content-center">
    <%= paginate @comments %>
   </div>
  </div>
 </div>
</div>

app/views/admin/comments/show.html.erb
<div class="container">
 <div class="row">

   <div class="col-sm-2 mt-3">
   <table class = "table-sm table-borderless">
    <thead>
     <th class="table-active h5">コメント詳細</th>
    </thead>
   </table>
  </div>
 </div>

   <%= form_with model: @comment, url: admin_comment_path(@comment), method: :patch, local:true do |f| %>
   <table class="table table-borderless">
    <tbody>
     <tr>
      <td>ニックネーム</td>
      <td><%= @comment.member.nickname %></td>
     </tr>
     <tr>
      <td>コメント内容</td>
      <td><%= @comment.content %></td>
     </tr>
     <tr>
      <td><%= f.label :is_active, "ステータス" %></td>
      <td>
       <%= f.radio_button :is_active, :on %>
       <%= f.label :is_active_on, "公開" %>
       <%= f.radio_button :is_active, :off %>
       <%= f.label :is_active_off, "非公開" %>
   　　</td>
     </tr>
     <tr>
      <td></td>
      <td><%= f.submit "更新する", class: "btn btn-success btn-lg mt-2 mb-2" %></td>
     </tr>
    </tbody>
   </table>
   <% end %>
  </div>
 </div>
</div>