config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :members
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :members, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do
  root to: 'homes#top'
  resources :genres, only: [:index, :create, :edit, :update]
  resources :members, only: [:index, :show, :edit, :update]
  resources :hobbyposts, only: [:index, :show, :update]
  resources :comments, only: [:index, :show, :update]
 end

 scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  resources :comments, only: [:show, :create]
  resources :members, only: [:show, :edit, :update]
  get '/members/:id/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
  patch '/members/:id/withdrawal' => 'members#withdrawal', as: 'withdrawal'
  resources :hobbyposts do
  resource :favorites, only: [:create, :destroy]
  end
 end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :hobbyposts
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
   @genre = Genre.new
   @genres = Genre.all
  end

  def create
   @genre = Genre.new(genre_params)
    if @genre.save
     redirect_to admin_genres_path
    else
     @genres = Genre.all
     render :index
    end
  end

  def edit
   @genre = Genre.find(params[:id])
  end

  def update
   @genre = Genre.find(params[:id])
   if @genre.update(genre_params)
    redirect_to admin_genres_path
   else
    render :edit
   end
  end

 private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
 <div class="row"> 
  <div class="col-sm-2 mt-3">
   <table class ="table-sm table-borderless">
    <thead>
     <th class="table-active h5">ジャンル編集</th>
    </thead>
   </table>
  </div>
 </div>

<%= form_with model: @genre, url: admin_genre_path(@genre), local: true do |f| %>
 <div class="row">
  <div class="col-sm-2 mt-5"><%= f.label :name, "ジャンル名" %></div>
  <div class="col-sm-3 mt-5"><%= f.text_field :name %></div>
  <div class="col-sm-3 mt-5"><%= f.submit "変更を保存", class: "btn btn-success btn-lg" %></div>
 </div>
<% end %>

app/views/admin/genres/index.html.erb
<div class="container">
 <div class="row"> 
  <div class="col-sm-4 mt-3">
   <table class ="table-sm table-borderless">
    <thead>
     <th class="table-active h5">ジャンル一覧・追加</th>
    </thead>
   </table>
  </div>
 </div>

<%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
 <div class="row">
  <div class="col-sm-2 mt-5"><%= f.label :name, "ジャンル名" %></div>
  <div class="col-sm-3 mt-5"><%= f.text_field :name %></div>
  <div class="col-sm-3 mt-5"><%= f.submit "新規登録", class: "btn btn-success btn-lg" %></div>
 </div>
<% end %>

 <div class="row">
  <div class="col-sm-4 mt-5">
   <table class ="table">
    <thead class = "thead-light">
     <tr>
      <th>ジャンル</th>
      <th></th>
     </tr>
    </thead>
    <tbody>
     <% @genres.each do |genre| %>
     <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success btn-sm btn-block mt-2 mb-2" %></td>
     </tr>
     <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>