config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :members
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :members, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do
  root to: 'homes#top'
  resources :genres, only: [:index, :create, :edit, :update]
  resources :members, only: [:index, :show, :edit, :update]
  resources :hobbyposts, only: [:index, :show, :update]
  resources :comments, only: [:index, :show, :update]
 end

 scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  resources :comments, only: [:show, :create]
  resources :members, only: [:show, :edit, :update]
  get '/members/:id/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
  patch '/members/:id/withdrawal' => 'members#withdrawal', as: 'withdrawal'
  resources :hobbyposts do
  resource :favorites, only: [:create, :destroy]
  end
 end

end

app/models/hobby_post.rb
class HobbyPost < ApplicationRecord
  belongs_to :genre
  belongs_to :member
  has_many :comments
  has_one_attached :image
   
  validates :introduction, :title, :genre_id, presence: { message: "が空になっています。" }
end

app/models/hobbypost.rb
class Hobbypost < ApplicationRecord
  belongs_to :genre
  belongs_to :member
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image

  #validates :introduction, :title, :genre_id, presence: { message: "が空になっています。" }
  with_options if: :status==true do
   validates :introduction, presence: true
   validates :title, presence: true
  end
  validates :introduction, length: { maximum: 400 }, on: :publicize
  validates :title, length: { maximum: 14 }, on: :publicize

  def favorited?(member)
   favorites.where(member_id: member.id).present?
  end

  enum is_active: { on: true,  off: false }
  #enum status: { 公開中: true,  下書き保存: false }

end

app/controllers/admin/hobbyposts_controller.rb
class Admin::HobbypostsController < ApplicationController
 def index
  @hobbyposts = Hobbypost.where(status: :true).order(params[:sort]).page(params[:page]).per(10)
 end

 def show
  @hobbypost = Hobbypost.find(params[:id])
 end

 def update
  @hobbypost = Hobbypost.find(params[:id])
  if @hobbypost.update(hobbypost_params)
   redirect_to admin_hobbyposts_path
   flash[:notice] = "投稿内容を更新しました。"
  else
   render :index
  end
 end

 private
 def hobbypost_params
  params.require(:hobbypost).permit(:is_active)
 end

end

app/helpers/admin/hobbyposts_helper.rb
module Admin::HobbypostsHelper
end

app/views/admin/hobbyposts/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-2 mt-3">
   <table class ="table-sm table-borderless">
    <thead>
     <th class="table-active h5">投稿一覧</th>
    </thead>
   </table>
  </div>
 </div>

 <div class="row">
  <div class="col-sm-12 mt-3"></div>
    <table class = "table table-borderless">
     <thead class = "thead-light">
      <tr>
       <th>投稿ID</th>
       <th>ジャンル</th>
       <th>タイトル</th>
       <th>投稿内容</th>
       <th>ステータス</th>
      </tr>
     </thead>

     <tbody>
      <% @hobbyposts.each do |hobbypost| %>
      <tr>
       <td><%= hobbypost.id %></td>
       <td><%= hobbypost.genre.name %></td>
       <td><%= link_to hobbypost.title, admin_hobbypost_path(hobbypost.id) %></td>
       <td><%= hobbypost.introduction %></td>
       <td><%= hobbypost.is_active %></td>
      </tr>
      <% end %>
     </tbody>
    </table>
  </div>
 </div>

 <div class="row">
  <div class="col-sm-12 mt-3">
   <div class="d-flex justify-content-center">
    <%= paginate @hobbyposts %>
   </div>
  </div>
 </div>
</div>

app/views/admin/hobbyposts/show.html.erb
<div class="container">
 <div class="row">

   <div class="col-sm-2 mt-3">
   <table class = "table-sm table-borderless">
    <thead>
     <th class="table-active h5">投稿詳細</th>
    </thead>
   </table>
  </div>
 </div>

 <div class="row">
  <div class="col-sm-5 mt-3">
    <% if @hobbypost.image.attached? %>
     <%= image_tag @hobbypost.image, size: "400x300" %>
    <% else %>
     <%= image_tag 'no_image', size: "400x300" %>
    <% end %>
  </div>
  <div class="col-sm-7 mt-3">

   <%= form_with model: @hobbypost, url: admin_hobbypost_path(@hobbypost), method: :patch, local:true do |f| %>
   <table class="table table-borderless">
    <tbody>
     <tr>
      <td>タイトル</td>
      <td><%= @hobbypost.title %></td>
     </tr>
     <tr>
      <td>ジャンル</td></td>
      <td><%= @hobbypost.genre.name %></td>
     </tr>
     <tr>
      <td>投稿内容</td>
      <td><%= @hobbypost.introduction %></td>
     </tr>
     <tr>
      <td><%= f.label :is_active, "ステータス" %></td>
      <td>
       <%= f.radio_button :is_active, :on %>
       <%= f.label :is_active_on, "公開" %>
       <%= f.radio_button :is_active, :off %>
       <%= f.label :is_active_off, "非公開" %>
   　　</td>
     </tr>
     <tr>
      <td></td>
      <td><%= f.submit "更新する", class: "btn btn-success btn-lg mt-2 mb-2" %></td>
     </tr>
    </tbody>
   </table>
   <% end %>
  </div>
 </div>

 <div class="row">
  <div class="col-sm-7 mt-3">
 <% if @hobbypost.comments.present? %>
  <% @hobbypost.comments.each do |comment| %>
   <%= comment.member.nickname %>さん
   <%= comment.content %>
   <%= comment.created_at %>
  <% end %>
 <% else %>
  コメントはありません。
 <% end %>
  </div>
 </div>
</div>