config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :members
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :members, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do
  root to: 'homes#top'
  resources :genres, only: [:index, :create, :edit, :update]
  resources :members, only: [:index, :show, :edit, :update]
  resources :hobbyposts, only: [:index, :show, :update]
  resources :comments, only: [:index, :show, :update]
 end

 scope module: :public do
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'
  resources :comments, only: [:show, :create]
  resources :members, only: [:show, :edit, :update]
  get '/members/:id/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
  patch '/members/:id/withdrawal' => 'members#withdrawal', as: 'withdrawal'
  resources :hobbyposts do
  resource :favorites, only: [:create, :destroy]
  end
 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :hobbypost
  
  enum is_active: { on: true,  off: false }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
 belongs_to :member
 belongs_to :hobbypost
 
 validates :member_id, uniqueness: { scope: :hobbypost_id } 
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :hobbyposts
end

app/models/hobby_post.rb
class HobbyPost < ApplicationRecord
  belongs_to :genre
  belongs_to :member
  has_many :comments
  has_one_attached :image
   
  validates :introduction, :title, :genre_id, presence: { message: "が空になっています。" }
end

app/models/hobbypost.rb
class Hobbypost < ApplicationRecord
  belongs_to :genre
  belongs_to :member
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image

  #validates :introduction, :title, :genre_id, presence: { message: "が空になっています。" }
  with_options if: :status==true do
   validates :introduction, presence: true
   validates :title, presence: true
  end
  validates :introduction, length: { maximum: 400 }, on: :publicize
  validates :title, length: { maximum: 14 }, on: :publicize

  def favorited?(member)
   favorites.where(member_id: member.id).present?
  end

  enum is_active: { on: true,  off: false }
  #enum status: { 公開中: true,  下書き保存: false }

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hobbyposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, through: :comments, source: :hobbypost, dependent: :destroy
  has_one_attached :image

  validates :email, presence: true, uniqueness: true
  validates :first_name, :last_name, :last_name_kana, :first_name_kana, :age, :nickname, presence: { message: "が空になっています。" }

  VALID_TELEPHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  validates :telephone_number, format: { with: VALID_TELEPHONE_NUMBER_REGEX }, presence: true

  validates :age, :numericality => {:only_integer => true, greater_than_or_equal_to: 15}

  validates :comment_text, presence: true, length: { maximum: 1000 }

  enum gender: { male: 0, female: 1 }
  enum is_active: { stay: true,  withdrawal: false }

  def full_name
   self.last_name + self.first_name
  end

  def favorited_by?(post_id)
   likes.where(post_id: post_id).exists?
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
 
 def index
  @comments = Comment.page(params[:page]).per(10)
 end

 def show
  @comment = Comment.find(params[:id])
 end

 def update
  @comment = Comment.find(params[:id])
  if @comment.update(comment_params)
   redirect_to admin_comments_path
   flash[:notice] = "ステータスを更新しました。"
  else
   render :index
  end
 end

 private
 def comment_params
  params.require(:comment).permit(:is_active)
 end
 
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
   @genre = Genre.new
   @genres = Genre.all
  end

  def create
   @genre = Genre.new(genre_params)
    if @genre.save
     redirect_to admin_genres_path
    else
     @genres = Genre.all
     render :index
    end
  end

  def edit
   @genre = Genre.find(params[:id])
  end

  def update
   @genre = Genre.find(params[:id])
   if @genre.update(genre_params)
    redirect_to admin_genres_path
   else
    render :edit
   end
  end

 private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
  
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController

 def index
  @members = Member.page(params[:page])
 end

 def show
  @member = Member.find(params[:id])
 end

 def edit
  @member = Member.find(params[:id])
 end

 def update
  @member = Member.find(params[:id])
  @member.update(member_params)
  redirect_to admin_member_path(@member.id)
 end

private
  def member_params
    params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :gender, :age, :telephone_number, :email, :is_active, :nickname)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :gender, :age, :nickname, :telephone_number])
  end
  
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/hobbyposts_helper.rb
module Admin::HobbypostsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>趣味る -syumiru-</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">趣味る</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
            <li class="col-sm-3 nav-item">
              <%= link_to '会員一覧', admin_members_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' %>
            </li>
            <li class="col-sm-3 nav-item ">
              <%= link_to '投稿一覧', admin_hobbyposts_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' %>
            </li>
            <li class="col-sm-3 nav-item ">
              <%= link_to 'コメント一覧', admin_comments_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' %>
            </li>
            <li class="col-sm-3 nav-item">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' %>
            </li>
            <li class="col-sm-3 nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark btn btn-outline-secondary btn-sm' %>
            </li>
            <% elsif member_signed_in? %>
            <li class="nav-item">
              <%= link_to "投稿一覧", hobbyposts_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_hobbypost_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', member_path(current_member.id), class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_member_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "趣味るとは？", about_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", hobbyposts_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_member_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <% flash.each do |key, value| %>
     <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>趣味を見つけよう！楽しもう！</p>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>